# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: ubuntu-latest
stages:
- stage: backend
  jobs:
  - job: 
    steps:
    - script: echo hello first
      displayName: first
  - job: testing_second
    steps:
    - script: echo hello second
      displayName: second